### PR TITLE
BD-13 | Update Project directory structure for Bigger projects

### PR DESCRIPTION
**Pull request by kshitiz-shresth**
Task Link: https://readytowork.atlassian.net/browse/BD-13

- [x] Updated directory structure
- [x] Route versioning
- [x] controller/repository/service seperation according to feature.

New Changes
- routes `{base_url}/api/v1/{feature}`
eg: `GET` http://127.0.0.1:5000/api/v1/users

### CODE REVIEW

**Review by sumitsapkota75 — COMMENTED** [review]
Please separate entity/app wise structure

/user 
controller.go
repository.go
services.go
/products 
controller.go
repository.go
services.go

**Review by bhattaraibishal50 — CHANGES_REQUESTED** [review]
@kshitiz-shresth 
There is merge conflict on the PR.

**Review by bhattaraibishal50 — DISMISSED** [review]
Looks Good to Me 🙇🏻

**Review by sumitsapkota75 — APPROVED** [review]
lgtm

**Pull request merged**
