### PR TITLE
BD-106 | Inject services through CLI tool

### PR DESCRIPTION
**Pull request by smooth-55**
[TASK](https://readytowork.atlassian.net/browse/BD-106)
============================================
## What I Did Here:
- Created a script that injects jwt authentication service into skeleton
## How To Inject Jwt Authentication Service:
-  Inside root directory of skeleton write command `make inject-jwt` in terminal and press enter key. It will inject jwt service and it also does `go mod tidy` to install required package for jwt

### CODE REVIEW

**Review by bhattaraibishal50 — APPROVED** [review]

**Review by sumitsapkota75 — APPROVED** [review]
LGTM 🙇

**Review by bhattaraibishal50 — APPROVED** [review]
**LGTM** 🙇🏻

**Comment by sawal-timsina** [comment]
@smooth-55 done exactly what we want, but the process is quite different than i had imagined. I have created a new [task](https://readytowork.atlassian.net/browse/BD-75) where i have explained the process, please work on it if you are interested.

**Comment by sawal-timsina** [comment]
@smooth-55 done exactly what we want, but the process is quite different than i had imagined. I have created a new [task](https://readytowork.atlassian.net/browse/BD-75) where i have explained the process, please work on it if you are interested.

**Pull request closed without merging**
